AllCops:
  SuggestExtensions: false
  NewCops: enable
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Metrics/CollectionLiteralLength:
  Exclude:
    - 'lib/german_phone_number_classifier/german_landline_prefixes.rb'
Metrics/ModuleLength:
  Exclude:
    - 'lib/german_phone_number_classifier/german_landline_prefixes.rb'
Metrics/MethodLength:
  Exclude:
    - 'lib/german_phone_number_classifier.rb'
