AllCops:
  SuggestExtensions: false
  NewCops: enable
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
Metrics/ModuleLength:
  Exclude:
    - 'lib/german_phone_number_classifier/german_landline_prefixes.rb'
